### ISSUE TITLE
Time series

### ISSUE THREAD

**Issue by ndvbd** [yandex-research/tabular-dl-revisiting-models#43]
Can this be applied to a time series? So that each token will represent a different point in time, and within each token there will be all the embeddings for all the features in this single time event? And that padding token is a 'missing' time event.

**Comment by ndvbd** [comment]
Any time series solution that uses tranformers + numerical features?

**Comment by Yura52** [comment]
Not sure that I understand the question

**Comment by ndvbd** [comment]
I mean, is there a similar solution to FFT, that is adapted to time series?

**Comment by Yura52** [comment]
I am sure that there are projects with Transformer-like models for time series data, but I am not sure if there are specifically adaptations of FT-Transformer.

In fact, if you simply want to apply Transformer to your data as you described, I think the shortest path is to implement it yourself. Basically, you need to encode your data to the shape `(batch_size, window_size, d_embedding)` and pass it to `rtdl.Transformer` or even to the built-in implementation: [link](https://pytorch.org/docs/stable/nn.html#transformer-layers).

Regarding easy-to-use packages, I am not very familiar with the relevant ecosystem, but here is one of the recent Transformer-like models: https://github.com/yuqinie98/PatchTST At the beginning of README, there are some libraries mentioned. So maybe this project and those libraries can be a starting point for your search.

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed!
